keys:
  - &fallback age1ha9wjtcmzu49nceqah00f70t4r2s7uzgqkt76quxkpgfzhz4u4aqagnr7x
  - &users:
    - &choffmann age1mvm3yv2tw7d6neus8hkefdhny9ja4qyzk229vpzhhd3wc6nr8c8sqev2st
  - &hosts:
    - &tuxedo age1nks4y4mmsdksg33gnpk20r40seckj0449vzmdqtyk5j2jzjqvpsqmm34tx
    - &homepc age19xaxx92erreapmscev25dswu8rygfpv3um28uwrt2tj6zl8qmgrqpq66r2
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
      - age:
          - *choffmann
          - *tuxedo
          - *homepc
          - *fallback
