keys:
  - &users:
    - &choffmann age1h6w5ljasnhqqv5ju5lk6c0yedzqaxlkx2vm3x0msj9els9km8veq7srjf8
  - &hosts:
    - &macbook age1h6w5ljasnhqqv5ju5lk6c0yedzqaxlkx2vm3x0msj9els9km8veq7srjf8
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
    - age:
      - *choffmann
      - *macbook
