keys:
  - &fallback age1ha9wjtcmzu49nceqah00f70t4r2s7uzgqkt76quxkpgfzhz4u4aqagnr7x
  - &users:
    - &choffmann age1mvm3yv2tw7d6neus8hkefdhny9ja4qyzk229vpzhhd3wc6nr8c8sqev2st
  - &hosts:
    - &tuxedo age1nks4y4mmsdksg33gnpk20r40seckj0449vzmdqtyk5j2jzjqvpsqmm34tx
    - &cho-progeek age1ct84sc7n2nwrmg65mwnqtjxjyk0d52nke860cg04lrphgn3zhctsrtvu4f
    - &homepc age16mrg8h87xz4prag6cjr9z43nu6dg8tem6spwtw3rw5zwzppss5asa4p7hl
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
      - age:
          - *choffmann
          - *tuxedo
          - *homepc
          - *cho-progeek
          - *fallback
